### PR TITLE
Added collaborator section to README

### PR DESCRIPTION
**Pull request by Nxybi**
# Summary
Changed the README to have a list of collaborators. Sorry not sorry for using a PR instead of pushing to stable.

## Changes

- [ ] This is a **MAJOR** change (e.g new class, rewrite)
- [ ] This is a minor change (e.g typo fixed, optimization, bugfix)
- [X] This does not effect any code (i.e README/documentation change)
  - [X] If needed, the documentation has been updated..

### CODE REVIEW

**Comment by Nicolas-Klatzer** [comment]
PR is a good way to do this though

**Comment by Nxybi** [comment]
> PR is a good way to do this though

shhhhhhhhhhh 
**shhhhhhhhhhhhhhhhhhhhhhhh**

**Comment by Nicolas-Klatzer** [comment]
I would say, though that the collaborators are added at the end of the readme, so if it gets a bit too big that you can still see stuff

**Review by Nicolas-Klatzer — CHANGES_REQUESTED** [review]
Should be moved to the end of the file for better readability

**Review by Nicolas-Klatzer — CHANGES_REQUESTED** [review]
looks good now

**Review by Nicolas-Klatzer — APPROVED** [review]

**Pull request merged**
